[package]
name = "control"
default-run = "control"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "definite"

[dependencies]
argh = "0.1"
libc = "0.2"
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true
